services:
    Symfony\Component\RateLimiter\RateLimiterFactory $collectionCommentLimiter: '@limiter.collection_comment'

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $tmdbApiKey: '%env(TMDB_API_KEY)%'
            $googleBooksApiKey: '%env(GOOGLE_BOOKS_API_KEY)%'
            $cache: '@cache.app'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
